#!/bin/bash

api_properties_file="local.properties.example"

local_properties_file="local.properties"

echo "# The following entries are automatically generated by a script" >> $local_properties_file

while IFS='=' read -r key _; do
    if [[ -n "$key" ]]; then
        value=$(printenv $key)

        if [[ -n "$value" ]]; then
            echo "$key=$value" >> $local_properties_file
        fi
    fi
done < $api_properties_file

echo "Selected environment variables have been appended to $local_properties_file."
